[package]
name = "hal-contract-mock-example"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
publish = false

[dependencies]
hal-contract = { path = "../../rust" }
async-trait = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
